services:
  - type: web
    name: dexchat-backend
    runtime: node
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/public-config

    envVars:
      # Runtime settings
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.16.0

      # Secrets & config — supply via Dashboard on first Blueprint apply
      - key: COINBASE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_APP_CERTIFICATE
        sync: false